# Generated by Django 3.0.8 on 2020-07-18 16:55

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField()),
                ('category', models.CharField(help_text='Please enter any one category listed as: Gurung Newar Magar Rai Sherpa Tamang ', max_length=100)),
                ('available', models.BooleanField(blank=True, default=True, null=True)),
                ('quantity', models.IntegerField(max_length=20)),
                ('size', models.CharField(help_text='Enter the available size seperated by comma ie , ', max_length=200)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('listed_date', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('thumbnail', models.ImageField(help_text='recommendate size is 500x775', upload_to=product.models.upload_thumbnail)),
                ('picture_1', models.ImageField(blank=True, help_text='recommendate size is 1000x1358', null=True, upload_to=product.models.upload_picture)),
                ('picture_2', models.ImageField(blank=True, help_text='recommendate size is 1000x1358', null=True, upload_to=product.models.upload_picture)),
                ('picture_3', models.ImageField(blank=True, help_text='recommendate size is 1000x1358', null=True, upload_to=product.models.upload_picture)),
            ],
        ),
    ]
