# Generated by Django 3.0.8 on 2020-07-29 16:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2020, 7, 29, 16, 36, 34, 523721, tzinfo=utc))),
                ('views', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
